### PR TITLE
Issue #49

### PR DESCRIPTION
**Pull request by anikets43**
Changed File Upload CSS.
Added font awesome cdn reference.

### CODE REVIEW

**Comment by anikets43** [comment]
@ptkach 
Image preview has been removed for now. Once it's styling is done, i will add it back. Kindly review and let me know for any changes.

Cheers,
Aniket

**Comment by ptkach** [comment]
Hi @anikets43,

Thanks a lot, overall impression is very good. I really like you design concept. Few moments I would like to point out for fix, before merging:

1) That's what I see when uploaded .gif and .jpeg files:

screen shot 2016-05-08 at 7 28 41 pm

Can you please finish with images and gifs to make it look good?

2) As for me currently file container is too big, I think it makes sense shrink it twice and place two containers in a row. That's gonna also affect my third point

3) I tried to upload folder with 10+ files and list has taken very significant height. I would say we need to restrict it to some max height with scrollbar. And if we have two files containers per row, it also supposed to be smaller. What do you think?

4) You have added <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css"> in index html. Here couple concerns about it:

1. First of all, index.html is there in development and demo purposes, but filelist is part of the npm package. So if it's included in html it's not going to be exported by users, which means they will not get this styles.
2. I would prefer to not add any extra dependencies. Try to extract styles you need from it and put it in local styles.css which you export from derectives.

Let me know if you find any of my points inappropriate. 

Thank you,
Pavlo

**Comment by ptkach** [comment]
Hi @anikets43,

Please responde, are you planning to proceed with it? 

Cheers,
Pavlo

**Comment by anikets43** [comment]
Hi @ptkach 
I will work on the above items on weekend.

Cheers,
Aniket

**Pull request closed without merging**
